name: BattleGrounds
version: 1.0
main: com.dev.csplaym.Plugin
api-version: 1.21
authors: [deva7727]
description: A CS:GO style minigame for Minecraft

commands:
  play:
    description: Join a BattleGrounds game
    usage: /play
  leave:
    description: Leave the current game
    usage: /leave
  bg:
    description: Admin commands for BattleGrounds
    usage: |
      /bg setspawn <map> <team1/team2> - Set team spawn point
      /bg create <map> - Create a new map
      /bg delete <map> - Delete a map
      /bg list - List all maps
    permission: battlegrounds.admin
    
permissions:
  battlegrounds.admin:
    description: Allows access to admin commands
    default: op
  battlegrounds.play:
    description: Allows players to join games
    default: true